version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/nginx
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports: 
        - "33060:3306"
    volumes:
      - store:/var/lib/mysql
volumes:
  store:
